const express = require('express');
const controller = require('../controllers/tiktokShopController');
const orderProductCategoryController = require('../controllers/orderProductCategoryController');

const adminRouter = express.Router();
adminRouter.get('/exchange-rates', controller.getExchangeRates);
adminRouter.get('/oauth/start', controller.startShopOauth);
adminRouter.get('/connections', controller.listShopConnections);
adminRouter.get('/shops', controller.listShops);
adminRouter.delete('/shops/:shopId', controller.disconnectShop);
adminRouter.get('/shops/:shopId/analytics', controller.getShopAnalytics);
adminRouter.post('/shops/:shopId/analytics/sync', controller.syncShopAnalytics);
adminRouter.get('/shops/:shopId/video-analytics', controller.listShopVideoPerformance);
adminRouter.post('/shops/:shopId/video-performance/sync', controller.syncVideoPerformanceApi);
adminRouter.get('/shops/:shopId/video-performance', controller.listVideoPerformanceApi);
adminRouter.post('/shops/:shopId/video-export/import', controller.importVideoPerformanceExport);
adminRouter.get('/shops/:shopId/video-export', controller.listVideoPerformanceExport);
adminRouter.get('/shops/:shopId/video-thumbnails/:videoId', controller.getShopVideoThumbnail);
adminRouter.get('/shops/:shopId/affiliate/open-collaborations', controller.listOpenCollaborations);
adminRouter.get('/shops/:shopId/affiliate/target-collaborations', controller.listTargetCollaborations);
adminRouter.get('/shops/:shopId/affiliate/orders', controller.listAffiliateOrders);
adminRouter.get('/shops/:shopId/affiliate/order-statistics', controller.listAffiliateOrderStatistics);
adminRouter.get('/shops/:shopId/order-management/categories', orderProductCategoryController.listCategories);
adminRouter.post('/shops/:shopId/order-management/categories', orderProductCategoryController.createCategory);
adminRouter.delete('/shops/:shopId/order-management/categories/:categoryId', orderProductCategoryController.deleteCategory);
adminRouter.put('/shops/:shopId/order-management/products/:productId/category', orderProductCategoryController.assignProduct);
adminRouter.delete('/shops/:shopId/order-management/products/:productId/category', orderProductCategoryController.unassignProduct);
adminRouter.get('/shops/:shopId/affiliate/creators', controller.listAffiliateCreators);
adminRouter.get('/shops/:shopId/affiliate/creators/:applicationId/fulfillments', controller.showAffiliateCreatorFulfillments);
adminRouter.get('/shops/:shopId/affiliate/marketplace-creators', controller.listMarketplaceCreators);
adminRouter.get('/shops/:shopId/affiliate/marketplace-creators/:creatorId', controller.showMarketplaceCreator);
adminRouter.post('/shops/:shopId/affiliate/marketplace-creators/:creatorId/invitations', controller.createMarketplaceCreatorInvitation);
adminRouter.post('/shops/:shopId/affiliate/marketplace-creators/:creatorId/invitations/:collaborationId/creators', controller.addMarketplaceCreatorToInvitation);
adminRouter.get('/shops/:shopId/affiliate/marketplace-creators/:creatorId/conversation', controller.getMarketplaceCreatorConversation);
adminRouter.post('/shops/:shopId/affiliate/marketplace-creators/:creatorId/conversation/messages', controller.sendMarketplaceCreatorMessage);
adminRouter.get('/shops/:shopId/affiliate/creator-content-details', controller.listCreatorContentDetails);
adminRouter.get('/shops/:shopId/creator-performance', controller.listCreatorPerformance);
adminRouter.post('/shops/:shopId/creator-performance/sync', controller.syncCreatorPerformance);
adminRouter.get('/shops/:shopId/affiliate/open-collaboration-settings', controller.showOpenCollaborationSettings);
adminRouter.delete('/connections/:authorizationId', controller.disconnectShopAuthorization);

module.exports = { adminRouter };
